#!/bin/bash

# Variables
KEY_NAME="bcitkey"
PUBLIC_KEY_PATH="$HOME/.ssh/$KEY_NAME.pub" 
KEY_EXISTS=$(aws ec2 describe-key-pairs --query "KeyPairs[?KeyName=='$KEY_NAME'].KeyName" --output text)


# Generate a new key pair
if [[ -f $PUBLIC_KEY_PATH ]]; then
  echo "Key pair '$KEY_NAME' is already created locally."
else
  echo "Creating $KEY_NAME ..."
  ssh-keygen -t ed25519 -f "$HOME/.ssh/$KEY_NAME" -C "$KEY_NAME" -N ""
  echo "Key pair '$KEY_NAME' is created."
fi

if [[ -n "$KEY_EXISTS" ]]; then
  echo "Key pair '$KEY_NAME' already exists in AWS."
  echo "Importing is skipped. 😮"
else
  echo "Importing '$KEY_NAME'..."
  
  # Import the public key to AWS
  public_ip=$(aws ec2 import-key-pair \
      --key-name "$KEY_NAME" \
      --public-key-material fileb://$PUBLIC_KEY_PATH \
      --region us-west-2 \
      --profile acit4640_admin \
      --output json)
  
  echo "Done 😊"
  echo $public_ip >> infrastructure_data
fi

    