#!/usr/bin/env bash

set -eu

# Variables
region="us-west-2"
key_name="bcitkey"

source ./infrastructure_data

# Get Ubuntu 23.04 image id owned by amazon
ubuntu_ami=$(aws ec2 describe-images --region $region \
 --owners amazon \
 --filters Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-lunar-23.04-amd64-server* \
 --query 'sort_by(Images, &CreationDate)[-1].ImageId' --output text)


# Create security group allowing SSH and HTTP from anywhere
security_group_id=$(aws ec2 create-security-group --group-name MySecurityGroup3 \
 --description "Allow SSH and HTTP" --vpc-id $vpc_id --query 'GroupId' \
 --region $region \
 --output text)

# Add /dev/null to the end of the command to suppress the output
aws ec2 authorize-security-group-ingress --group-id $security_group_id \
 --protocol tcp --port 22 --cidr 0.0.0.0/0 --region $region >> /dev/null

aws ec2 authorize-security-group-ingress --group-id $security_group_id \
 --protocol tcp --port 80 --cidr 0.0.0.0/0 --region $region >> /dev/null

sleep 10

# Launch an EC2 instance in the public subnet
# COMPLETE THIS PART
instance_id=$(aws ec2 run-instances \
    --security-group-ids $security_group_id \
    --image-id $ubuntu_ami \
    --count 1 \
    --instance-type t2.micro \
    --key-name $key_name \
    --associate-public-ip-address \
    --subnet-id $subnet_id \
    --query "Instances[0].InstanceId" \
    --output text)
echo "Instance '$instance_id' is created."


# wait for ec2 instance to be running
aws ec2 wait instance-running --instance-ids $instance_id

# Get the public IP address of the EC2 instance
# COMPLETE THIS PART
public_ip=$(aws ec2 describe-instances \
    --instance-ids $instance_id \
    --query "Reservations[0].Instances[0].PublicIpAddress" \
    --output text)
echo "Public IP '$public_ip' is contained."

# Write instance data to a file
# COMPLETE THIS PART
echo "ubuntu_ami=$ubuntu_ami" >> infrastructure_data
echo "key_name=$key_name" >> infrastructure_data
echo "instance_id=$instance_id" >> infrastructure_data
echo "public_ip=$public_ip" >> infrastructure_data
echo "security_group_id=$security_group_id" >> infrastructure_data
